TEXTS = {
    "ar": {
        "welcome": "أهلًا بك في AI Creator Studio",
        "subscribe_required": "يجب عليك الاشتراك أولًا في القناة لاستخدام البوت.",
        "check_subscription": "تحقق من الاشتراك",
        "join_channel": "اشترك في القناة",
        "subscription_ok": "تم التحقق من الاشتراك بنجاح ✅",
        "subscription_fail": "لم يتم التحقق من اشتراكك بعد. اشترك أولًا ثم أعد التحقق.",
        "main_menu": "اختر من القائمة الرئيسية:",
        "content_ideas": "🧠 أفكار محتوى",
        "captions": "✍️ كابشن",
        "hashtags": "#️⃣ هاشتاغات",
        "video_script": "🎬 سكربت فيديو",
        "coins": "💰 رصيدي",
        "language": "🌐 تغيير اللغة",
        "image_ai": "🖼️ إنشاء صورة",
        "video_ai": "🎥 إنشاء فيديو",
        "invite_friends": "👥 دعوة الأصدقاء",
        "my_referrals": "📊 عدد الدعوات",
        "ask_topic_content": "اكتب المجال أو نوع المحتوى الذي تريد أفكارًا له.",
        "ask_topic_caption": "اكتب وصفًا قصيرًا للمحتوى وسأكتب لك كابشن.",
        "ask_topic_hashtags": "اكتب موضوع المحتوى وسأعطيك هاشتاغات مناسبة.",
        "ask_topic_script": "اكتب فكرة الفيديو وسأكتب لك سكربت قصير.",
        "your_coins": "رصيدك الحالي: {coins} Coins",
        "language_changed": "تم تغيير اللغة بنجاح.",
        "choose_language": "اختر اللغة:",
        "not_understood": "اختر من الأزرار أو اكتب /start",
        "result_title": "النتيجة:",
        "your_referral_count": "عدد الدعوات الناجحة: {count}/3",
        "referral_message": "هذا رابطك الخاص لدعوة الأصدقاء:\n{link}\n\nعند دخول 3 أصدقاء من رابطك ستُفتح ميزات الصور والفيديو.",
        "premium_locked": "لفتح هذه الميزة يجب:\n1) الاشتراك في القناة\n2) دعوة 3 أصدقاء عبر رابطك الخاص",
        "premium_unlocked": "تم فتح هذه الميزة لك ✅",
        "image_prompt": "اكتب وصف الصورة التي تريد إنشاءها.",
        "video_prompt": "اكتب وصف الفيديو الذي تريد إنشاءه.",
        "image_coming": "ميزة إنشاء الصور ستُربط لاحقًا بمحرك الصور. الشرط تم التحقق منه ✅",
        "video_coming": "ميزة إنشاء الفيديو ستُربط لاحقًا بمحرك الفيديو. الشرط تم التحقق منه ✅",
    },
    "en": {
        "welcome": "Welcome to AI Creator Studio",
        "subscribe_required": "You must join the channel first to use the bot.",
        "check_subscription": "Check subscription",
        "join_channel": "Join channel",
        "subscription_ok": "Subscription verified successfully ✅",
        "subscription_fail": "Your subscription could not be verified yet. Join first, then try again.",
        "main_menu": "Choose from the main menu:",
        "content_ideas": "🧠 Content Ideas",
        "captions": "✍️ Captions",
        "hashtags": "#️⃣ Hashtags",
        "video_script": "🎬 Video Script",
        "coins": "💰 My Coins",
        "language": "🌐 Change Language",
        "image_ai": "🖼️ Create Image",
        "video_ai": "🎥 Create Video",
        "invite_friends": "👥 Invite Friends",
        "my_referrals": "📊 Referrals Count",
        "ask_topic_content": "Write your niche or topic and I will generate content ideas.",
        "ask_topic_caption": "Write a short description and I will create a caption.",
        "ask_topic_hashtags": "Write the topic and I will generate suitable hashtags.",
        "ask_topic_script": "Write the video idea and I will create a short script.",
        "your_coins": "Your current balance: {coins} Coins",
        "language_changed": "Language changed successfully.",
        "choose_language": "Choose a language:",
        "not_understood": "Choose from the buttons or type /start",
        "result_title": "Result:",
        "your_referral_count": "Successful referrals: {count}/3",
        "referral_message": "This is your personal invite link:\n{link}\n\nWhen 3 friends join using your link, image and video features will unlock.",
        "premium_locked": "To unlock this feature you must:\n1) Join the channel\n2) Invite 3 friends using your personal link",
        "premium_unlocked": "This feature is unlocked for you ✅",
        "image_prompt": "Write the image prompt you want to generate.",
        "video_prompt": "Write the video prompt you want to generate.",
        "image_coming": "Image generation will be connected later. Requirement verified ✅",
        "video_coming": "Video generation will be connected later. Requirement verified ✅",
    },
    "de": {
        "welcome": "Willkommen bei AI Creator Studio",
        "subscribe_required": "Du musst zuerst dem Kanal beitreten, um den Bot zu nutzen.",
        "check_subscription": "Abo prüfen",
        "join_channel": "Kanal beitreten",
        "subscription_ok": "Abo erfolgreich bestätigt ✅",
        "subscription_fail": "Dein Abo konnte noch nicht bestätigt werden. Bitte zuerst beitreten und dann erneut prüfen.",
        "main_menu": "Wähle aus dem Hauptmenü:",
        "content_ideas": "🧠 Content-Ideen",
        "captions": "✍️ Captions",
        "hashtags": "#️⃣ Hashtags",
        "video_script": "🎬 Video-Skript",
        "coins": "💰 Mein Guthaben",
        "language": "🌐 Sprache ändern",
        "image_ai": "🖼️ Bild erstellen",
        "video_ai": "🎥 Video erstellen",
        "invite_friends": "👥 Freunde einladen",
        "my_referrals": "📊 Einladungen",
        "ask_topic_content": "Schreibe deine Nische oder dein Thema, und ich erstelle Content-Ideen.",
        "ask_topic_caption": "Schreibe eine kurze Beschreibung, und ich erstelle eine Caption.",
        "ask_topic_hashtags": "Schreibe das Thema, und ich erstelle passende Hashtags.",
        "ask_topic_script": "Schreibe die Video-Idee, und ich erstelle ein kurzes Skript.",
        "your_coins": "Dein aktuelles Guthaben: {coins} Coins",
        "language_changed": "Sprache erfolgreich geändert.",
        "choose_language": "Wähle eine Sprache:",
        "not_understood": "Wähle eine Schaltfläche oder tippe /start",
        "result_title": "Ergebnis:",
        "your_referral_count": "Erfolgreiche Einladungen: {count}/3",
        "referral_message": "Das ist dein persönlicher Einladungslink:\n{link}\n\nWenn 3 Freunde über deinen Link starten, werden Bild- und Video-Funktionen freigeschaltet.",
        "premium_locked": "Um diese Funktion freizuschalten, musst du:\n1) Dem Kanal beitreten\n2) 3 Freunde über deinen Link einladen",
        "premium_unlocked": "Diese Funktion ist für dich freigeschaltet ✅",
        "image_prompt": "Schreibe die Bildbeschreibung.",
        "video_prompt": "Schreibe die Videobeschreibung.",
        "image_coming": "Die Bildfunktion wird später angebunden. Voraussetzung erfüllt ✅",
        "video_coming": "Die Videofunktion wird später angebunden. Voraussetzung erfüllt ✅",
    },
    "tr": {
        "welcome": "AI Creator Studio'ya hoş geldin",
        "subscribe_required": "Botu kullanmak için önce kanala katılmalısın.",
        "check_subscription": "Aboneliği kontrol et",
        "join_channel": "Kanala katıl",
        "subscription_ok": "Abonelik başarıyla doğrulandı ✅",
        "subscription_fail": "Aboneliğin henüz doğrulanamadı. Önce katıl, sonra tekrar kontrol et.",
        "main_menu": "Ana menüden seç:",
        "content_ideas": "🧠 İçerik Fikirleri",
        "captions": "✍️ Açıklamalar",
        "hashtags": "#️⃣ Etiketler",
        "video_script": "🎬 Video Senaryosu",
        "coins": "💰 Bakiyem",
        "language": "🌐 Dili Değiştir",
        "image_ai": "🖼️ Görsel Oluştur",
        "video_ai": "🎥 Video Oluştur",
        "invite_friends": "👥 Arkadaş Davet Et",
        "my_referrals": "📊 Davet Sayısı",
        "ask_topic_content": "Alanını veya konunu yaz, sana içerik fikirleri oluşturayım.",
        "ask_topic_caption": "Kısa bir açıklama yaz, sana caption hazırlayayım.",
        "ask_topic_hashtags": "Konuyu yaz, sana uygun hashtagler oluşturayım.",
        "ask_topic_script": "Video fikrini yaz, sana kısa bir senaryo hazırlayayım.",
        "your_coins": "Mevcut bakiyen: {coins} Coins",
        "language_changed": "Dil başarıyla değiştirildi.",
        "choose_language": "Bir dil seç:",
        "not_understood": "Butonlardan birini seç veya /start yaz",
        "result_title": "Sonuç:",
        "your_referral_count": "Başarılı davetler: {count}/3",
        "referral_message": "Bu senin kişisel davet linkin:\n{link}\n\n3 arkadaşın bu linkten girerse görsel ve video özellikleri açılır.",
        "premium_locked": "Bu özelliği açmak için:\n1) Kanala katıl\n2) Kişisel linkinle 3 arkadaş davet et",
        "premium_unlocked": "Bu özellik senin için açıldı ✅",
        "image_prompt": "Oluşturmak istediğin görsel açıklamasını yaz.",
        "video_prompt": "Oluşturmak istediğin video açıklamasını yaz.",
        "image_coming": "Görsel özelliği sonra bağlanacak. Şart doğrulandı ✅",
        "video_coming": "Video özelliği sonra bağlanacak. Şart doğrulandı ✅",
    },
}